#!/bin/bash

set -e

PGVERSION=${PGVERSION:=$1}
if [[ -z "$PGVERSION" ]]; then
    echo "Usage: $0 \$version"
    exit 32
fi

[[ $PGVERSION =~ ^[0-9]$ ]] && PGVERSION+=.0

curl -O https://salsa.debian.org/postgresql/postgresql-common/-/raw/master/pgdg/apt.postgresql.org.sh
sudo sh apt.postgresql.org.sh -i -v $PGVERSION
sudo pg_createcluster --start $PGVERSION test -p 5432 -- -A trust

if [[ ! -z "$GITHUB_PATH" ]]; then
    echo "/usr/lib/postgresql/$POSTGRES/bin" >> $GITHUB_PATH
fi
