#!/bin/bash

set -e

docker run --rm -d -e ISC_PASSWORD=nix -e FIREBIRD_DATABASE=sqitchtest.db -p 3050:3050 jacobalberty/firebird:${FIREBIRD:=latest}
sudo add-apt-repository -y ppa:mapopa/firebird3.0
sudo apt-get update -qq
sudo apt-get install -qq firebird-dev firebird3.0-utils
export FIREBIRD_HOME=/usr
export FIREBIRD_URI=db:firebird://sysdba:nix@localhost//firebird/data/sqitchtest.db
