#!/bin/bash

if [ $MYSQLVERSION = 'system' ]; then
    exit
fi

# Derived from https://github.com/PyMySQL/PyMySQL/blob/master/.travis/initializedb.sh
set -e
sudo service mysql stop
docker pull ${MYSQLVERSION}
RUN_MYSQL="docker run -it --name=mysqld -d -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -p 3306:3306"
export MYSQL_URI=db:mysql://root@127.0.0.1/information_schema

if [ $MYSQLVERSION == 'mysql:8.0' ]; then
    ${RUN_MYSQL} ${MYSQLVERSION} --default-authentication-plugin=mysql_native_password
else
    ${RUN_MYSQL} ${MYSQLVERSION}
fi

# No need to wait for it to start, lots of stuff gets installed after this,
# enough time goes by.
