#!/bin/bash

set -e

# Set up Snowflake.
sudo apt-get update -qq
sudo apt-get install -qq unixodbc-dev odbcinst unixodbc

# Install snowsql.
curl -o snowsql.bash http://sfc-snowsql-updates.s3.us-west-2.amazonaws.com/bootstrap/1.1/linux_x86_64/snowsql-1.1.72-linux_x86_64.bash
sed -e '1,/^exit$/d' snowsql.bash | tar zxf -
./snowsql -Uv
sudo mv snowsql /bin/

# TODO: Install Snowflake ODBC driver and config.

# TODO: Configure with actual Snowflake account.
export SNOWSQL_URI=db:snowflake://username:password@accountname/dbname?Driver=Snowflake;warehouse=warehouse
