#!/bin/bash

set -e

sudo apt-get update -qq
sudo apt-get install -qq unixodbc-dev odbcinst unixodbc
cat t/odbc/vertica.ini | sudo tee -a /etc/vertica.ini
docker run -d -p 5433:5433 --rm cjonesy/docker-vertica:${VERTICA:=latest}
docker ps -a
curl -sSLO --insecure https://my.vertica.com/client_drivers/8.1.x/8.1.1-7/vertica-client-8.1.1-7.x86_64.tar.gz
sudo tar -xzf vertica-client-8.1.1-7.x86_64.tar.gz -C /
export PATH=/opt/vertica/bin:$PATH
export VSQL_URI=db:vertica://dbadmin@localhost:5433/docker?Driver=Vertica
