=head1 Name

sqitch-tag - Create or list tag objects

=head1 Synopsis

  sqitch [options] tag
  sqitch [options] tag name
  sqitch [options] tag [-m MESSAGE] name

=head1 Description

Tag the latest change in the plan, or list the existing tags. This is useful
for preparing for a release. Tags are also required in order to rework a
change.

If called with name specified, a list of the current tags will be output.

=head1 Options

=over

=item C<-m>

=item C<--message>

A brief message describing the tag. The message will be attached to the tag as
a comment. Multiple invocations will be concatenated together as separate
paragraphs.

=back

=head1 Configuration Variables

None currently.

=head1 Sqitch

Part of the L<sqitch> suite.
