=begin private

Keep private so it's not displayed, but will still be indexed by the CPAN
toolchain.

=head1 Name

sqitchguides - List of common Sqitch guides

=end private

The common Sqitch guides are:

  changes             Specifying changes for Sqitch
  configuration       Hierarchical engine and target configuration
  environment         Environment variables
  authentication      Specifying target authentication credentials
  tutorial            PostgreSQL Tutorial
  tutorial-firebird   Firebird Tutorial
  tutorial-mysql      MySQL Tutorial
  tutorial-oracle     Oracle Tutorial
  tutorial-sqlite     SQLite Tutorial
  tutorial-vertica    Vertica Tutorial
  tutorial-exasol     Exasol Tutorial
  tutorial-snowflake  Snowflake Tutorial

See C<< sqitch help <command> >> or C<< sqitch help <concept> >> to read about
a specific command or concept.
