=head1 Name

sqitch-plan-usage - Sqitch plan usage statement

=head1 Usage

  sqitch plan [options] [<database>]

=head1 Options

Search options:

 -t --target <target>             database target specifying the plan
    --event                       type of event
    --change-pattern  --change    match regex against change names
    --planner-pattern --planner   match regex against committer names
 -n --max-count                   show only specified number of events
    --skip                        skip the specified number of events
    --reverse                     show events in reverse order
    --no-reverse                  don't show events in reverse order

Formatting

 -f --format                      show events in the specified format
    --date-format     --date      show dates in the specified format
    --color                       use ANSI colors
    --no-color                    never use ANSI colors
    --abbrev                      abbreviate change IDs
    --oneline                     shorthand for --format oneline --abbrev 6
    --headers                     show headers for plan file and project
    --no-headers                  don't show plan headers

