=head1 Name

sqitch-checkout-usage - Sqitch checkout usage statement

=head1 Usage

  sqitch [options] checkout branchname

=head1 Options

       --mode <mode>           deploy failure reversion mode (all, tag, or change)
       --verify                run verify scripts after deploying each change
       --no-verify             do not run verify scripts
    -s --set                   set a database client variable
    -r --set-revert            set a database client revert variable
    -r --set-deploy            set a database client deploy variable
       --log-only              log changes without running them
    -y                         disable the prompt before reverting
