=head1 Name

sqitch-add-usage - Sqitch add usage statement

=head1 Usage

  sqitch [options] add [change options] [<template options>] changename

=head1 Options

    -r --requires             require change
    -c --conflicts            declare conflicting change
    -s --set                  set a template variable
    -n --note                 a note describing the change

    -t --template             name of the templates to use
       --template-directory   path to directory containing templates
       --use [template=path]  path to named template

       --with    [script]     create named script
       --without [script]     do not create named script
    -e --edit, --open-editor  open change scripts in an editor
