=head1 Name

sqitch-target-usage - Sqitch target usage statement

=head1 Usage

  sqitch [options] target
  sqitch target [-v | --verbose]
  sqitch target add <name> <uri> [-s <property>=<value> ...]
  sqitch target alter <name> [-s <property>=<value> ...]
  sqitch target remove <name>
  sqitch target rename <old> <new>
  sqitch target show <name>

=head1 Options

    -v, --verbose             be verbose; must be placed before an action
    -s, --set     KEY=VALUE   set target property when adding a target
