=head1 Name

sqitch-revert-usage - Sqitch revert usage statement

=head1 Usage

  sqitch [options] revert [<target options>]

=head1 Options

       --to-target <tag>    revert to target
    -s --set                set a database client variable
       --log-only           log changes without running them
    -y                      disable the prompt before reverting
