=head1 Name

sqitch-revert-usage - Sqitch revert usage statement

=head1 Usage

  sqitch [options] revert [<change options>]

=head1 Options

       --to --change --to-change <change>  revert to change
    -s --set                               set a database client variable
       --log-only                          log changes without running them
    -y                                     disable the prompt before reverting
