=head1 Name

sqitch-checkout - Revert, checkout another VCS branch, and re-deploy changes

=head1 Synopsis

  sqitch [options] checkout [<database>] <branch>

=head1 Description

Checkout another branch in your project's VCS (such as
L<git|https://git-scm.org/>), while performing the necessary database changes
to update your database for the new branch.

More specifically, the C<checkout> command compares the plan in the current
branch to that in the branch to check out, identifies the last common changes
between them, reverts to that change as if L<C<sqitch revert>|sqitch-revert>
was called (unless there have been no changes deployed since that change),
checks out the new branch, and then deploys all changes as if
L<C<sqitch deploy>|sqitch-deploy> had been called.

If the VCS is already on the specified branch, nothing will be done.

The C<< <database> >> parameter specifies the database to which to connect,
and may also be specified as the C<--target> option. It can be target name,
a URI, an engine name, or plan file path.

=head1 Options

=over

=item C<-t>

=item C<--target>

The target database to which to connect. This option can be either a URI or
the name of a target in the configuration.

=item C<--mode>

Specify the reversion mode to use in case of failure. Possible values are:

=over

=item C<all>

In the event of failure, revert all deployed changes, back to the point at
which deployment started. This is the default.

=item C<tag>

In the event of failure, revert all deployed changes to the last
successfully-applied tag. If no tags were applied during this deployment, all
changes will be reverted to the point at which deployment began.

=item C<change>

In the event of failure, no changes will be reverted. This is on the
assumption that a change is atomic, and thus may may be deployed again.

=back

=item C<--verify>

Verify each change by running its verify script, if there is one. If a verify
test fails, the deploy will be considered to have failed and the appropriate
reversion will be carried out, depending on the value of C<--mode>.

=item C<--no-verify>

Don't verify each change. This is the default.

=item C<-s>

=item C<--set>

Set a variable name and value for use by the database engine client, if it
supports variables. The format must be C<name=value>, e.g., C<--set
defuser='Homer Simpson'>. Overrides any values loaded from the
C<deploy.variables> or C<revert.variables> configurations.

=item C<-d>

=item C<--set-deploy>

Set a variable name and value for use by the database engine client when
deploying, if it supports variables. The format must be C<name=value>, e.g.,
C<--set defuser='Homer Simpson'>. Overrides any values from C<--set> or loaded
from the C<deploy.variables> configuration.

=item C<-r>

=item C<--set-revert>

Sets a variable name to be used by the database engine client during when
reverting, if it supports variables. The format must be C<name=value>, e.g.,
C<--set defuser='Homer Simpson'>. Overrides any values from C<--set> or loaded
from the C<deploy.variables> and C<revert.variables> configurations.

=item C<--log-only>

Log the changes as if they were deployed, but without actually running the
deploy scripts. Useful for an existing database that is being converted to
Sqitch, and you need to log changes as deployed because they have been
deployed by other means in the past.

=item C<-y>

Disable the prompt that normally asks whether or not to execute the revert.

=back

=head1 Configuration Variables

=over

=item C<[deploy.variables]>

=item C<[revert.variables]>

A section defining database client variables. The C<deploy.variables>
configuration is read from the C<deploy> command configuration, on the
assumption that the values will generally be the same. If they're not, use
C<revert.variables> to override C<deploy.variables>.

These variables are useful if your database engine supports variables in
scripts, such as PostgreSQL's
L<C<psql> variables|https://www.postgresql.org/docs/current/static/app-psql.html#APP-PSQL-INTERPOLATION>,
Vertica's
L<C<vsql> variables|https://my.vertica.com/docs/7.1.x/HTML/index.htm#Authoring/ConnectingToHPVertica/vsql/Variables.htm>,
MySQL's
L<user variables|https://dev.mysql.com/doc/refman/5.6/en/user-variables.html>,
SQL*Plus's
L<C<DEFINE> variables|https://docs.oracle.com/cd/B19306_01/server.102/b14357/ch12017.htm>,
and Snowflake's
L<SnowSQL variables|https://docs.snowflake.net/manuals/user-guide/snowsql-use.html#using-variables>.

=item C<checkout.verify>

=item C<deploy.verify>

Boolean indicating whether or not to verify each change after deploying it.

=item C<checkout.mode>

=item C<deploy.mode>

Deploy mode. The supported values are the same as for the C<--mode> option.

=item C<[checkout.no_prompt]>

=item C<[revert.no_prompt]>

A boolean value indicating whether or not to disable the prompt before
executing the revert. The C<checkout.no_prompt> variable takes precedence over
C<revert.no_prompt>, and both may of course be overridden by C<-y>.

=item C<[checkout.prompt_accept]>

=item C<[revert.prompt_accept]>

A boolean value indicating whether default reply to the prompt before
executing the revert should be "yes" or "no". The C<checkout.prompt_accept>
variable takes precedence over C<revert.prompt_accept>, and both default to
true, meaning to accept the revert.

=back

=head1 Sqitch

Part of the L<sqitch> suite.
