=head1 Name

sqitch-status-usage - Sqitch status usage statement

=head1 Usage

  sqitch [<db-options>] status [<options>] [<database>]

=head1 Options

    -t --target                database to which to connect
       --project               project for which to retrieve the status
       --show-changes          include a list of deployed changes
       --show-tags             include a list of applied tags
       --date-format           display dates using the specified format
