=head1 Name

sqitch-help - Display help for Sqitch and Sqitch commands

=head1 Synopsis

  sqitch help [command]

=head1 Description

With no command given, the L<sqitch documentation|sqitch> is printed to
standard output. If a sqitch command is named, the documentation for that
command will be displayed.

=head1 Sqitch

Part of the L<sqitch> suite.
