=head1 Name

sqitch-rebase-usage - Sqitch rebase usage statement

=head1 Usage

  sqitch [options] rebase [revert-change options [deploy-change options]] [<database>]

=head1 Options

    -t --target <target>              database to which to connect
       --onto --onto-change <change>  revert to change
       --upto --upto-change <change>  deploy to change
       --mode <mode>                  deploy reversion mode (all, tag, change)
       --verify                       run verify scripts after each change
       --no-verify                    do not run verify scripts
    -s --set <key=value>              set a database client variable
    -r --set-revert <key=value>       set a database client revert variable
    -r --set-deploy <key=value>       set a database client deploy variable
       --log-only                     log changes without running them
    -y                                disable the prompt before reverting
