=head1 Name

sqitch-deploy-usage - Sqitch deploy usage statement

=head1 Usage

  sqitch [options] deploy [change options] [<database>]

=head1 Options

    -t --target <target>    database to which to connect
       --to-change <change> deploy to change
       --mode <mode>        failure reversion mode
    -s --set <key=value>    set a database client variable
       --verify             run verify scripts after each change
       --no-verify          do not run verify scripts
       --log-only           log changes without running them
