=head1 Name

sqitch-verify-usage - Sqitch verify usage statement

=head1 Usage

  sqitch [options] verify [<verify options>]

=head1 Options

       --from-change <change>  verify from change
       --to-change   <change>  verify to change
    -s --set                   set a database client variable
