=head1 Name

sqitch-tag-usage - Sqitch tag usage statement

=head1 Usage

  sqitch tag [options] <tagname> [<change>] [<target>]

=head1 Options

    -t --tag        <tag>     name of the tag to add
    -c --change     <change>  name of the change to tag
    -a --all                  tag all project plans
    -n --note       <note>    a note describing the tag
    -f --plan-file  <file>    path to a deployment plan file
       --top-dir    <dir>     path to directory with plan and scripts
