=begin private

Keep private so it's not displayed, but will still be indexed by the CPAN
toolchain.

=head1 Name

sqitchusage - Sqitch usage statement

=end private

=head1 Usage

  sqitch <command> [<options>] [<command-options>] [<args>]

=head1 Options

  -P --plan-file  <file>    Path to a deployment plan file.
  -C --directory  <dir>     Change to directory before performing any actions.
  -D --top-dir    <dir>     Path to directory with plan and scripts.
     --etc-path             Print the path to the etc directory and exit.
     --no-pager             Do not pipe output into a pager.
     --quiet                Quiet mode with non-error output suppressed.
  -V --verbose              Increment verbosity.
     --version              Print the version number and exit.
     --help                 Show a list of commands and exit.
     --man                  Print the introductory documentation and exit.
