=head1 Name

sqitch-deploy-usage - Sqitch deploy usage statement

=head1 Usage

  sqitch [options] deploy [<change options>]

=head1 Options

       --to-change <change> deploy to change
       --mode <mode>        failure reversion mode
    -s --set                set a database client variable
       --verify             run verify scripts after each change
       --no-verify          do not run verify scripts
       --log-only           log changes without running them
