=head1 Name

sqitch-status - Show the current deployment status of a database

=head1 Synopsis

  sqitch [options] status [<options>] [<database>]

=head1 Description

Displays information about the current deployment status of a database. The
most recently deployed change information is displayed, as well as any related
tags. If there are undeployed changes in the plan, they will be listed.
Otherwise, a message will indicate that the database is up-to-date.

The C<< <database> >> parameter specifies the database to which to connect,
and may also be specified as the C<--target> option. It can be target name,
a URI, an engine name, or plan file path.

=head1 Options

=over

=item C<-t>

=item C<--target>

The target database to which to connect. This option can be either a URI or
the name of a target in the configuration.

=item C<--project>

Project for which to retrieve the status. Defaults to the status of the
current project, if a plan can be found.

=item C<--show-changes>

Also display a list of deployed changes.

=item C<--show-tags>

Also display a list of applied tags.

=item C<--date-format>

=item C<--date>

Format to use for timestamps. Defaults to C<iso>. Allowed values:

=over

=item C<iso>

=item C<iso8601>

Shows timestamps in ISO-8601 format.

=item C<rfc>

=item C<rfc2822>

Show timestamps in RFC-2822 format.

=item C<full>

=item C<long>

=item C<medium>

=item C<short>

Show timestamps in the specified format length, using the system locale's
C<LC_TIME> category.

=item C<raw>

Show timestamps in raw format, which is strict ISO-8601 in the UTC time zone.

=item C<strftime:$string>

Show timestamps using an arbitrary C<strftime> pattern. See
L<DateTime/strftime Paterns> for comprehensive documentation of supported
patterns.

=item C<cldr:$string>

Show timestamps using an arbitrary C<cldr> pattern. See L<DateTime/CLDR
Paterns> for comprehensive documentation of supported patterns.

=back

=back

=head1 Configuration Variables

=over

=item C<status.show_changes>

Boolean value indicates whether or not to display changes in the output.
Defaults to false.

=item C<status.show_tags>

Boolean value indicates whether or not to display tags in the output. Defaults
to false.

=item C<status.date_format>

Format to use for timestamps. Supports the same values as the C<--date-format>
option.

=back

=head1 Sqitch

Part of the L<sqitch> suite.
