=head1 Name

sqitch-add-usage - Sqitch add usage statement

=head1 Usage

  sqitch [options] add [<change-options>] [<template-options>] name

=head1 Options

    -r --requires             require change
    -c --conflicts            declare conflicting change
    -s --set                  set a template variable
    -m --message              set a message describing

       --template-directory   path to directory containing templates
       --deploy-template      path to deploy template
       --revert-template      path to revert template
       --test-template        path to test template

       --no-deploy            do not create deploy script
       --no-revert            do not create revert script
       --no-test              do not create test script
       --deploy               create deploy script
       --revert               create revert script
       --test                 create test script
