#!/usr/bin/env perl -CAS

use FindBin;
use lib "$FindBin::Bin/..";
use lib "$FindBin::Bin/../lib";
use POSIX qw (setlocale);
BEGIN {
    if ($^O eq 'MSWin32') {
        require Win32::Locale;
        setlocale Win32::Locale::get_locale(), '';
    } else {
        setlocale POSIX::LC_MESSAGES, '';
    }
}
use App::Sqitch;

exit App::Sqitch->go;
