#!/usr/bin/env perl -CAS

use FindBin;
use lib "$FindBin::Bin/..";
use lib "$FindBin::Bin/../lib";

use POSIX qw (setlocale LC_MESSAGES);
setlocale LC_MESSAGES, '';
use App::Sqitch;

exit App::Sqitch->go;
